feat: Add battery reading wrapper
blackspherefollower/buttplug4j pull request #46
Opened 2024-11-14 16:58 UTC by Fyustorm

This change introduces hasBatterySensor, readBatteryLevel, and sendSensorReadCmd to handle battery level reading from devices. These functions allow checking for a battery sensor, reading the battery level, and sending a sensor read command to the device.

2024-11-14 16:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/blackspherefollower/buttplug4j?pullRequest=46) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/blackspherefollower/buttplug4j?pullRequest=46) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/blackspherefollower/buttplug4j?pullRequest=46) it.</sub>

2024-11-17 14:19 UTC, blackspherefollower commented on buttplug4j/src/main/java/io/github/blackspherefollower/buttplug4j/client/ButtplugClientDevice.java
> +        final SensorReadCmd cmd = new SensorReadCmd(index, index);
I think the first argument here should be `deviceIndex`

2024-11-17 14:20 UTC, blackspherefollower requested changes
I think one of the index's is off

2024-11-18 06:56 UTC, blackspherefollower requested changes

2024-11-18 06:56 UTC, blackspherefollower commented on buttplug4j/src/main/java/io/github/blackspherefollower/buttplug4j/client/ButtplugClientDevice.java
> +        final SensorReadCmd cmd = new SensorReadCmd(this.deviceIndex, ButtplugConsts.DEFAULT_MSG_ID);
Ah, just realised the messageId has to be set from `client.getNextMsgId()`: the response will have the same messageId, which is what ties up the future handling.

2024-11-18 17:04 UTC, Fyustorm commented
In the last commit I changed to client.getNextMsgId() and I also added a timeout in the readBatteryLevel because in the case the device crashed or anything else it would hangs up indefinitely

2024-11-19 09:24 UTC, merged